### ISSUE TITLE
Bottone "Cancella Profilo"

### ISSUE THREAD

**Issue by drigoni** [TECWEBUnipd/SitesBoard#10]
Il file deleteProfile funziona perfettamente. Occorre inserire il pulsante

**Comment by jack793** [comment]
> Inserito e collegato il pulsante per rimuovere il profilo; è in rosso e dentro una fieldset apposita centrata a fine pagina "profile.cgi"

**Comment by jack793** [comment]
Devo ancora inserire pagina e css aggiornati perchè devo ancora sistemare tutte le cartelle come da server.
