### ISSUE TITLE
Gli accenti danno problemi nel database.xml

### ISSUE THREAD

**Issue by drigoni** [TECWEBUnipd/SitesBoard#24]
Software error:

../data/database.xml:9: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xE9 0x20 0x6D 0x69
n programmatore esperto in Java, C++ e ho lavorato per la Google (5 minuti perch
                                                                                ^
For help, please send mail to the webmaster (webmaster@localhost), giving this error message and the time and date of the error.

Software error:

[Fri Jan 29 21:54:02 2016] profile.cgi: ../data/database.xml:9: parser error : Input is not proper UTF-8, indicate encoding !
[Fri Jan 29 21:54:02 2016] profile.cgi: Bytes: 0xE9 0x20 0x6D 0x69
[Fri Jan 29 21:54:02 2016] profile.cgi: n programmatore esperto in Java, C++ e ho lavorato per la Google (5 minuti perch
[Fri Jan 29 21:54:02 2016] profile.cgi:                                                                                 ^
Compilation failed in require at profile.cgi line 8.
For help, please send mail to the webmaster (webmaster@localhost), giving this error message and the time and date of the error.

**Comment by jack793** [comment]
ma in che pagina del sito ti ha dato sto problema?

**Comment by drigoni** [comment]
profile.cgi

**Comment by jack793** [comment]
a me visualizza bene e tutte le var sono encodizzate quindi controlla..fai screen se persiste

**Comment by drigoni** [comment]
Ha smesso con i file nuovi.

**Comment by jack793** [comment]
ottimo
