### ISSUE TITLE
cambiare colori blu e viola dei link del sito

### ISSUE THREAD

**Issue by Fasolato** [TECWEBUnipd/SitesBoard#44]
un marrone che funzione è HEX: #800000
un blu che funzione è HEX: #0000CD
un rosso che funzione è HEX: #FF0000
un verde che funzione è HEX: #228B22

**Comment by drigoni** [comment]
Prendete i colori da qui: http://www.w3schools.com/colors/colors_hex.asp
Scrivete nella relazione da dove li abbiamo presi.
Ricordatevi non colori troppo strani, ma cercate di seguire il colore che in automatico dovrebbe essere.
